### ISSUE TITLE
Request for Export on pressing enter key

### ISSUE THREAD

**Issue by NRblubanyan** [SunSpecOrangeButton/ob-openapi-editor#30]
The export button does not correspond to being selected with the Enter key, which instead refreshes the page and clears out your work. This can be quite frustrating for users who are very familiar with using the Enter key to submit other types of forms. It would be nice if the export button would be selected when pressing Enter

**Comment by shelcrow** [comment]
#17 fix was supposed to fix this. It works on my system (Windows 10, Chrome). What OS and browser are you using?
