### ISSUE TITLE
Newly-created ItemType not available to assign to elements

### ISSUE THREAD

**Issue by cwhanse** [SunSpecOrangeButton/ob-openapi-editor#70]
I created a new ItemType using the Item Types Editor feature. I can see the new ItemType in the editor using the View All Item Types feature. However, when editing a Definition, I cannot find the new ItemType in the pull-down list when using the Change Item Type feature.

**Comment by shelcrow** [comment]
I wasn't able to recreate this bug. Can you give an example of the Item Type and the definition you are adding to?

**Comment by cwhanse** [comment]
In this [file](https://gist.github.com/cwhanse/1fe53354d79baf8d8bced694dac01075), there is a new `inverterStyleItemType` which I can't assign to the `InverterStyle` element.

**Comment by shelcrow** [comment]
It works on my end. Can you clear the browser cache for the site and see if that fixes it?

**Comment by cwhanse** [comment]
Ok, I found how it works. No need to clear the cache. The ItemTypes are alphabetized, but the names include the taxonomy prefix, e.g., `solar-types:`. The new ItemType has no taxonomy prefix so appears as `inverterStyleItemType` and I was looking for it in the `solar-types` group.

Can we add a search feature for this list? Or maybe there's a more natural ordering?  The list comprises two large groups:
- item types starting with a Capital letter in alphabetical order
- all other item types in alphabetical order, and if there is a taxonomy prefix, the first letter of that prefix determines position.

Also, what is the rule for capitalization in an item type name?

**Comment by shelcrow** [comment]
I will create an issue for adding a search feature. The sorting is based on ASCII value so capital letters come before lower case in the sort, we can change that to a more natural ordering.

Currently there is no rule about capitalization for item types.

**Comment by cwhanse** [comment]
Replaced by #71 and #72
